#!/usr/bin/env bash

curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default1&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default2&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default3&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default4&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default5&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default6&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default7&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default8&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default9&format=csv"
curl -O "http://localhost:6006/data/plugin/scalars/scalars?tag=train_loss_epoch&run=default10&format=csv"

# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run1_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run2_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run3_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run4_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run5_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run6_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run7_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run8_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run9_seed_393589&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run10_seed_393589&format=csv"

# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run1_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run2_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run3_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run4_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run5_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run6_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run7_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run8_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run9_seed_147923&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run10_seed_147923&format=csv"

# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run1_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run2_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run3_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run4_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run5_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run6_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run7_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run8_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run9_seed_278346&format=csv"
# curl -O "http://localhost:6006/experiment/defaultExperimentId/data/plugin/scalars/scalars?tag=train_loss_epoch&run=00031_run10_seed_278346&format=csv"